パッケージの更新
sohosai/teaser23 pull request #41
Opened 2023-11-08 16:21 UTC by oka4shi

dependabotに怒られまくってるので全体的にパッケージを更新。
破壊的変更は特になさそう。

2023-11-08 16:30 UTC, oka4shi commented
https://github.com/sohosai/teaser23/pull/30#issuecomment-1741644301
この問題がまだ解決していないようなのでastro-i18n-autをv0.4.16にダウングレード

2023-11-08 16:40 UTC, oka4shi commented
手元の環境ではSharpを導入済みにも関わらずT以下のエラーが出ている。

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

MissingSharp: Could not find Sharp. Please install Sharp (`sharp`) manually into your project or migrate to another image service.
    at loadSharp (file:///home/goahi/Documents/Repos/teaser23/dist/chunks/astro-assets-services_81ce89ad.mjs:344:11)
    at async Object.transform (file:///home/goahi/Documents/Repos/teaser23/dist/chunks/astro-assets-services_81ce89ad.mjs:356:15)
    at async generateImageInternal (file:///home/goahi/Documents/Repos/teaser23/node_modules/astro/dist/assets/build/generate.js:107:24)
    at async generateImage (file:///home/goahi/Documents/Repos/teaser23/node_modules/astro/dist/assets/build/generate.js:54:28)
    at async file:///home/goahi/Documents/Repos/teaser23/node_modules/p-queue/dist/index.js:118:36 {
  loc: undefined,
  title: 'Could not find Sharp.',
  hint: "See Sharp's installation instructions for more information: https://sharp.pixelplumbing.com/install. If you are not relying on `astro:assets` to optimize, transform, or process any images, you can configure a passthrough image service instead of installing Sharp. See https://docs.astro.build/en/reference/errors/missing-sharp for more information.\n" +
    '\n' +
    'See https://docs.astro.build/en/guides/images/#default-image-service for more information on how to migrate to another image service.',
  frame: undefined,
  type: 'AstroError'
}
```

2023-11-08 16:46 UTC, oka4shi commented
上と同じ理由かもしれないが、`npm run dev`時に画像が読み込めないという問題が生じている。

また、astro-iconも追従できていないらしく、
```
node_modules/astro-icon/lib/utils.ts (2:9) "Props" is not exported by "node_modules/astro-icon/lib/Props.ts", imported by "node_modules/astro-icon/lib/utils.ts".
node_modules/astro-icon/lib/utils.ts (2:16) "Optimize" is not exported by "node_modules/astro-icon/lib/Props.ts", imported by "node_modules/astro-icon/lib/utils.ts".
```
というエラーが出る

2023-11-18 14:45 UTC, oka4shi commented
> 上と同じ理由かもしれないが、`npm run dev`時に画像が読み込めないという問題が生じている。
> 
> また、astro-iconも追従できていないらしく、
> 
> ```
> node_modules/astro-icon/lib/utils.ts (2:9) "Props" is not exported by "node_modules/astro-icon/lib/Props.ts", imported by "node_modules/astro-icon/lib/utils.ts".
> node_modules/astro-icon/lib/utils.ts (2:16) "Optimize" is not exported by "node_modules/astro-icon/lib/Props.ts", imported by "node_modules/astro-icon/lib/utils.ts".
> ```
> 
> というエラーが出る

これはastro-iconにIssueが立っていて、どうやらv3.0から発生しているようだ。
とりあえず表示が崩れたりといったことはないので、いったん無視してしまっても問題ないかもしれない。

2023-11-29 09:59 UTC, appare45 requested changes
ダメそう…
![image](https://github.com/sohosai/teaser23/assets/64473501/4e23a4ce-fed5-4f89-84af-4f5a5918fc7a)

2024-01-26 12:47 UTC, closed without merging